### ISSUE TITLE
Modelo relacional

### ISSUE THREAD

**Issue by JulioCesar69** [SistemasTecTlaxiaco/diseno-de-bases-de-datos-relacional-pc-box#2]
[Modelo de Base de datos relacional.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-bases-de-datos-relacional-pc-box/files/6361692/Modelo.de.Base.de.datos.relacional.pdf)

**Comment by 10154** [comment]
la práctica se desarrollo de una forma entendible, por ello obtuvo un porcentaje de 20%.

**Comment by josealfredo79** [comment]
Bien hecho...y revisado
